import streamlit as st


# Add the visual title to the actual page
st.title("🤖 UniCompanion")

# Setup header and progress bar
st.progress(0.0)
col_meta1, col_meta2 = st.columns([1, 1])
with col_meta1:
    st.caption(f"🆔 **Participant:** ID-{st.session_state.participant_id}")
st.markdown("---")

# The function that triggers the native page swap
def accept_consent():
    st.session_state.responses["consent_given"] = True
    st.switch_page("pages/2_demographics.py")

# Page Content
st.subheader("📄 Consent Form")
with st.container(border=True):
    st.markdown("### Purpose of the Study")
    st.write("The purpose of this study is to evaluate and compare different types of Retrieval-Augmented Generation (RAG) chatbot systems designed to assist students with administrative and study regulation queries.")
    
    st.markdown("### Procedure")
    st.write("You will be asked to review question-and-response pairs generated by four different chatbots. For each chatbot, you will evaluate a series of interactions based on specific quality metrics. After completing each chatbot's evaluation block, you will fill out a short survey regarding your perception of the agent's trustworthiness and transparency.\n\nThe entire study is conducted online, must be completed on a computer or laptop (mobile devices are not suitable), and is estimated to take approximately 20 minutes.")
    
    st.markdown("### Possible Risks and Discomforts")
    st.write("There are no physical or psychological risks associated with this study. The tasks involve reading text and completing standard questionnaires. You may experience mild cognitive fatigue due to the evaluative nature of the task. Participation is entirely **voluntary**, and you are free to withdraw from the experiment at any time without giving a reason and without any penalty. In case of incomplete participation, the collected data will not be recorded.")
    
    st.markdown("### Possible Benefits")
    st.write("This study may not provide direct personal benefits. However, the findings will contribute to research on Human-Computer Interaction (HCI), Explainable AI (XAI), and the development of more reliable, transparent conversational agents for educational institutions. As compensation for your participation, eligible students (e.g., those studying cognitive science and psychology) can receive 0.5 VP-Stunden. Additionally, all participants will have the opportunity to enter a raffle for a €100 voucher.")
    st.markdown("### Privacy and Data Protection")
    st.write("All data collected during this experiment including your evaluation ratings, survey responses, and basic demographic questions will be recorded anonymously. No personal identifying information will be collected. The anonymized data will be stored securely on Google infrastructure (which includes servers located in the US) and will be accessed exclusively by the authorized research team for academic purposes.")
    st.write("If you have any questions, concerns, or complaints about this study, please contact:\n\n**Researcher:** mamini@uni-osnabrueck.de")
    st.markdown("---")
    st.markdown("#### Declaration of Consent")
    st.markdown("By clicking the **'I Agree and Start'** button below, you declare that:\n* You have read and understood the information above.\n* You are at least 18 years of age.\n* You have a level of English proficiency sufficient to complete the tasks.\n")
    st.markdown("<br>", unsafe_allow_html=True)
    
    # Button triggers the switch
    if st.button("I Agree and Start", use_container_width=True):
        accept_consent()
