import streamlit as st

# --- BASIC SESSION GUARD ---
# Check if they passed the consent page
if "responses" not in st.session_state or "consent_given" not in st.session_state.responses:
    st.switch_page("pages/1_consent.py")


# 2. Add the visual title to the actual page
st.title("🤖 UniCompanion")

st.progress(0.2)
col_meta1, col_meta2 = st.columns([1, 1])
with col_meta1:
    st.caption(f"🆔 **Participant:** ID-{st.session_state.participant_id}")
st.markdown("---")

def go_to_role_reminder():
    st.switch_page("pages/4_role_reminder.py")

st.subheader("📖 Experiment Instructions")
st.write("Welcome! Thank you for participating in our study. Please read the following guidelines carefully before starting the evaluation.")

with st.container(border=True):
    st.markdown("### Your Task")
    st.write(f"You will evaluate {len(st.session_state.block_order)} different chatbots sequentially. Each chatbot represents a different approach designed to answer student queries about Cognitive Science administration and study regulations at Osnabrück University.\n\nFor each chatbot, the evaluation is split into two phases:")
    st.markdown("#### Phase 1: System Evaluation")
    st.write("You will be presented with a series of interactions. For each interaction, you will see:\n* **The Student's Question:** The query submitted to the chatbot.\n* **The Expected Response:** The verified, correct administrative answer.\n* **The Original Context:** The source documentation/regulations retrieved by the system.\n* **The Chatbot Response:** The response generated by the chatbot based on the original context.\n\nFor each interaction, you must evaluate the chatbot's output using the provided sliding scales/metrics.\n\n💡 *Tip: If you are unsure about the definition of any evaluation metric, hover over or click the help sign [?] located next to the metric name for a detailed explanation.*")
    st.markdown("#### Phase 2: Post-Block Survey")
    st.write("After you finish evaluating the set of questions for a specific chatbot, you will complete a brief survey. In this survey, you will rate how trustworthy and transparent you found that specific conversational agent based on your experience.")
    st.markdown("### Important Rules for Participation")
    st.write("* **Do not refresh or close the browser tab** during the experiment, as your progress will be lost.\n* Please complete the study in a quiet environment where you can focus.\n* Please evaluate the chatbot responses objectively based on the provided context and the expected response, rather than personal assumptions about university rules.")
    
    st.markdown("<br>", unsafe_allow_html=True)
    if st.button("Proceed to Scenario →", use_container_width=True):
        go_to_role_reminder()